name: CI

on:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          # h.el is currently broken for emacs > 27.2.
          # The issue comes from a directory-files-recursively API change.
          # TODO: get rid of that functino
#          - 25.1
#          - 25.2
#          - 25.3
#          - 26.1
#          - 26.2
#          - 26.3
#          - 25.1
#          - 25.2
          - 27.2
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v2
    - name: Run tests
      run: make
